version: "3"

services:
  postgres:
    image: "postgres:14-alpine"
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    container_name: "postgres-deadflowers"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    image: backend-deadflowers-dev
    env_file:
      - backend.env
      - postgres.env
    links:
      - "postgres:database"
    ports:
      - "5000:5000"
    container_name: "backend-deadflowers-dev"
    volumes:
      - ./services/backend:/app
    depends_on:
      - redis
      - worker
      - postgres

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.dev
    image: frontend-deadflowers-dev
    volumes:
      - ./services/frontend:/app
    ports:
      - "8080:8080"
    container_name: "frontend-deadflowers-dev"

  redis:
    image: "redis:alpine"
    environment:
      - REDIS_PASSWORD=test123
    ports:
      - "6379:6379"
    volumes:
      - "redis:/var/lib/redis/data"
    container_name: "redis-deadflowers"

  worker:
    build:
      context: ./services/backend
      dockerfile: ./app/worker/Dockerfile.dev
    image: worker-deadflowers-dev
    env_file:
      - backend.env
      - postgres.env
    container_name: "worker-deadflowers-dev"
    links:
      - "postgres:database"
    volumes:
      - ./services/backend/app:/app/app
    depends_on:
      - postgres

volumes:
  postgres: null
  redis: null
