version: "2"

services:
  postgres:
    image: "postgres:14-alpine"
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    container_name: "postgres-deadflowers"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
    restart: unless-stopped

  backend:
    build: ./services/backend
    image: backend-deadflowers
    env_file:
      - backend.env
      - postgres.env
    links:
      - "postgres:database"
      - "worker"
    ports:
      - "5000:5000"
    container_name: "backend-deadflowers"
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_started }
    restart: unless-stopped

  frontend:
    build: ./services/frontend
    image: frontend-deadflowers
    links:
      - backend
    ports:
      - "8080:8080"
    container_name: "frontend-deadflowers"
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis:/var/lib/redis/data"
    container_name: "redis-deadflowers"
    restart: unless-stopped

  worker:
    build:
      context: ./services/backend
      dockerfile: ./app/worker/Dockerfile
    image: worker-deadflowers
    env_file:
      - backend.env
      - postgres.env
    container_name: "worker-deadflowers"
    links:
      - "postgres:database"
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_started }
    restart: unless-stopped

volumes:
  postgres: null
  redis: null
