version: "3.9"

services:
  postgres:
    image: "postgres:14.0-alpine"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
    ports:
    - "5432:5432"
    container_name: "postgres-deadflowers"
    volumes:
    - postgres:/var/lib/postgresql/data
  
  backend:
    build: ./services/backend
    links:
      - "postgres:database"
    environment:
      - PROJECT_NAME=RecipeMountain
      - FIRST_SUPERUSER=admin@example.com
      - FIRST_SUPERUSER_PASSWORD=admin
      - POSTGRES_SERVER=database:5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "5000:5000"
    container_name: "backend-deadflowers"
    depends_on:
      - postgres
  
  frontend:
    build: ./services/frontend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider # required for node to start, bug with current version of node 
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"
    container_name: "frontend-deadflowers"
  
  worker:
    build: ./services/celery
    command: celery worker --app=worker.celery --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    container_name: "worker-deadflowers"

  redis:
    image: "redis:alpine"
    environment:
      - REDIS_PASSWORD=test123
    ports:
      - "6379:6379"
    volumes:
      - "redis:/var/lib/redis/data"
    container_name: "redis-deadflowers"

volumes:
  postgres:
    name: postgres
  redis:
    name: redis
    
