version: "3"

services:
  postgres:
    image: "postgres:14.0-alpine"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    container_name: "postgres-deadflowers"
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build: ./services/backend
    env_file:
      - backend.env
    links:
      - "postgres:database"
    ports:
      - "5000:5000"
    container_name: "backend-deadflowers"
    depends_on:
      - postgres
      - redis
      - worker

  frontend:
    build: ./services/frontend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider # required for node to start, bug with current version of node 
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"
    container_name: "frontend-deadflowers"

  redis:
    image: "redis:alpine"
    environment:
      - REDIS_PASSWORD=test123
    ports:
      - "6379:6379"
    volumes:
      - "redis:/var/lib/redis/data"
    container_name: "redis-deadflowers"

  worker:
    build: ./services/backend
    command: celery worker --app=app.worker.app.celery --loglevel=info
    env_file:
      - backend.env
    container_name: "worker-deadflowers"
    links:
      - "postgres:database"
    depends_on:
      - postgres

volumes:
  postgres: null
  redis: null
